#!/bin/bash

if [[ $1 == "--build" || $1 == "--install" || $1 == "-E" || $1 == "--help" ]]; then
    cmake "$@"
else
    cmake \
        -DCMAKE_CROSSCOMPILING=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_TOOLCHAIN_FILE=${WINE_CROSSTOOLCHAIN}/CrossWindows.cmake \
        \
        "$@"
fi

