#!/bin/bash

if [[ $1 == "--build" || $1 == "--install" || $1 == "-E" || $1 == "--help" ]]; then
    cmake "$@"
else
    cmake \
        -DCMAKE_CROSSCOMPILING=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_TOOLCHAIN_FILE=${WINE_CROSSTOOLCHAIN}/CrossWindows.cmake \
        -DCMAKE_C_COMPILER=wx-cl \
        -DCMAKE_CXX_COMPILER=wx-cl \
        -DCMAKE_LINKER=wx-link \
        -DCMAKE_RC_COMPILER=wx-rc \
        -DCMAKE_MT=wx-mt \
        \
        "$@"
fi

